### ISSUE TITLE
Incompatibility with Django 1.8

### ISSUE THREAD

**Issue by PetrDlouhy** [silverfix/django-nested-inlines#25]
This aplication fails in Django 1.8rc1 with following error:

    File "/env/src/django-nested-inlines/nested_inlines/admin.py", line 133, in NestedModelAdmin
    @transaction.commit_on_success
    AttributeError: 'module' object has no attribute 'commit_on_success'

It is because commit_on_success has been removed in this version

**Comment by PetrDlouhy** [comment]
There is another problem with Django 1.8 when I try to see the admin page:

    Traceback (most recent call last):
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 125, in get_response
     response = middleware_method(request, callback, callback_args, callback_kwargs)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 82, in process_view
      response = panel.process_view(request, view_func, view_args, view_kwargs)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/debug_toolbar_line_profiler/panel.py", line 176, in process_view
      out = self.profiler.runcall(view_func, *args, **view_kwargs)
    File "/usr/lib/python2.7/cProfile.py", line 149, in runcall
      return func(*args, **kw)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
      return self.admin_site.admin_view(view)(*args, **kwargs)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
      response = view_func(request, *args, **kwargs)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
      response = view_func(request, *args, **kwargs)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
      return view(request, *args, **kwargs)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
      return bound_func(*args, **kwargs)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
      response = view_func(request, *args, **kwargs)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
      return func.__get__(self, type(self))(*args2, **kwargs2)
    File "/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/src/django-nested-inlines/nested_inlines/admin.py", line 287, in change_view
      queryset=inline.queryset(request))
    AttributeError: 'CompanyAdminInline' object has no attribute 'queryset'

**Comment by vivazzi** [comment]
This problem is solved by the replacing inline.queryset(request) to inline.get_queryset(request) in nested_inlines/admin.py.
django 1.6 has .get_queryset instead of .queryset

For comparison:
https://docs.djangoproject.com/en/1.5/ref/contrib/admin/#inlinemodeladmin-options
https://docs.djangoproject.com/en/1.6/ref/contrib/admin/#inlinemodeladmin-options
